set +x
echo 'https link https://github.com'
echo 'http link http://github.com'
echo 'no scheme link github.com'
echo 'link with path github.com/github/octocat'
echo 'github.com start of line'
echo 'end of line github.com'
echo 'quotes "github.com"'
echo 'tab \t"github.com"'
echo 'https + .git link https://github.com/github/octocat.git'
echo 'ANSI RED link is parsed and changed to blue \e[1;31mhttps://github.com\e[0m'
echo 'Partial ANSI RED link is chunked and not parsed https://\e[1;31mgithub\e[0m.com'
echo 'LAVENDER background, but encompasses the link, is parsed \e[45m link to https://github.com\e[0m with other text'
