name: check-oidc-audience
run-name: "ran-by-${{ github.actor }}"
on:
  push

permissions:
    id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run some tests
        id: test
        run: |
          AUTH_TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange"
          | jq -r '.value')
          SPLIT="$(cut -d'.' -f2 <<<"$AUTH_TOKEN")" 
          echo "$SPLIT" | base64 -d | jq -r .aud
