name: test
run-name: "ran-by-${{ github.actor }}"
on:
  push

permissions:
    id-token: write
    contents: read

jobs:
  test:
    runs-on: linux-standard
    steps:
      - name: run some tests
        id: test
        run: echo "hello"